### ISSUE TITLE
EMSE paper

### ISSUE THREAD

**Issue by mauricioaniche** [SuelenGC/master-degree-dissertation#9]
Improvements points based on our ICSME 2018 rejection.

# Reviewer 1

- [x] E01 The number of participants is quite limited, especially in the first step (answering research question RQ1). It is a great threat to the validity.

- [x] E02 It is not clear how participants are recruited, which have significant influence on the conclusions. By the way, additional information about such participants are needed. For example, how many companies are involved? What kind of apps are they working on?

- [x] E03 "we only considered a code smell a category if the number of responses was greater or equal to five" why is 'five' used? Referring to a reference is not enough. The underling rational should be presented as well.

- [x] E04 (same as E13) In the first part of the study, answers to ‘good practices’ are collected as well. How are such answers analyzed and how do them help to make conclusions? Details are missing.

- [x] E05 The second part (step 2) is biased. Participants may tend to say yes to all questions. A potential way to solve this issues it to include some good practice as FALSE SMELLS, which may reveal who (and to what extent) are biased.

- [x] E06 The third part (step 3): who selected the code snips? How did they select? Design and implementation problems are far beyond code smells: the latter is only a small part of the former, especially in this paper code smells is confined to those specific to the presentation layers.  As a result, other factors instead of the specified code smells may dominate the results. To reduce the threats, we should exclude such responses that fail to specify the pre-defined smells. Although the paper (page 8) analyzes the problems pointed out by participants, it does not specify how often the intended smells are pointed out, or how often other problems are specified. 

- [x] E07 Some smells in Section 4 are not confined to presentation layers, e.g., obscure names.  Could you explain why they are confined to presentation?

- [x] E08 the third paragraph on the left column: while investigating whether components affected by smells are perceived as problematic when compared to clean classes, why should we use the answers to Q3  (severity) instead of answers to Q1 (problematic or not)? As specified on page 4, only if the given code snip is problematic, participants should answer Q3. 

- [x] E09 the last paragraph on the right column: why not exclude duplicate participants?

# Reviewer 2

- [x] E10 My first question regards the choice of limiting the analysis to Android. Why? As the authors performed multiple surveys, they did not have tooling limits and might have collected a much larger of answers, besides being able to generalize the catalog of smells to the entire set of mobile platforms available so far.

- [x] E11 Step 1: The authors nicely explained the typical steps of Grounded Theory, however they did not report details on the process followed. For instance, I could not understand who performed the task: was it assigned to one of the authors? Were the activities performed double-checked somehow?

- [x] E12 Step 1: Starting from a total of 810 answers, only 352 of them were considered, i.e., 57% of the collected answers was discarded: on the one hand, this data highlights that most of the developers who performed the survey did not take the task seriously: the authors should discuss this point in the threats to validity. Much more importantly, it seems that in the end the opinions of only 19 developers were considered: I wonder whether such a number is enough to elicit a catalog of code smells. To partially account for this problem, the authors should actively discuss the experience of the developers whose answers were considered, instead of reporting the experience of all the respondents. 

- [x] E13 Step 1: It is unclear the role of the questions related to the best practices. As the authors wanted to elicit a catalog of code smells, why did they consider the best practice too? And, more importantly, how did the authors analyze the answers on best practices during the Grounded Theory phase?

- [x] E14 Step 1: As a final step of the elicitation procedure, the authors took into account the bad practices cited by developers at least 5 times. They motivate this choice citing a paper of Nielsen where the author reported that "five repetitions is enough to characterize a recurring problem, and the following repetitions tend not to aggregate new relevant information": fair enough, but the survey under consideration was performed by a very small number of developers. Nielsen referred to surveys having hundrends/thousands of participants: the authors should motivate better the choice. 

- [x] E15 RQ2: How did the authors share the questionnaire? It was much more successful than the first one (201 answers vs 45): is there a motivation? 

- [x] E16 RQ2: The authors sold this study as a "confirmatory survey": this is generally good, but my main problem is that they did not allow the respondents to propose further code smells. In other words, the problem of eliciting the smells based on the answers of a very small number of developers has not been addressed.

- [x] E17 RQ2: The authors explained the survey questions, but it is really hard to properly understand them without seeing the actual questions. Rather than discussing the questions, I warmly invite the authors to report a table containing the actual questions presented to developers. 

- [x] E18 RQ2: The third section of the survey aims at collecting answers on the developers' perception of code smells. What is the relation between this part of the study and the third research question? Did the authors use the answers collected in this stage to answer RQ3? Why did the authors present statements that "denied the affirmations related to the perceived frequency of the code smell"?

- [x] E19 RQ2: Before running the questionnaire, the authors interviewed two Android developers with the aim of validating the statements that were later presented in the survey. How did the interviews were conducted? Were they semi-structured? What was their focus and what was requested to the interviewees?

- [x] E20 In RQ3, the authors recruited 70 developers. They could only evaluate 7 of the 20 proposed code smells. Why? If the experiment comprised random questions related to all the smells, why did not the authors evaluate the effect of all of them? How many answers per smell did they receive?

- [x] E21 RQ3: The analysis of the results should be improved. The authors discuss the achieved findings, but I would have liked to see more qualitative explanations. For instance, they found that "only three smells were considered less important": is there a motivation for this? In the "too many or too few fragments?" case, why did developers have contradictory opinions? What was reported in their answers?

- [x] E22 "This questionnaire was based on an instrument used by Aniche et al. [7], [7] to search for code smells in MVC applications": what does it mean? Did you use a tool? Which one?

# Reviewer 3

- [x] E23 The authors conduced three different studies. Of course such studies are highlight “coupled”. However, to improve the readability of the paper I strongly suggest presenting after the design of each study also the relative results. This is because the results of a study are used as starting point of the subsequent study. The current version of the paper, instead, present the design of the three studies and then the results achieved. However, some design choices becomes clear just after reading the discussion of the results. This because, design choices are in some cases trigged by the results achieved in the prior study.

- [x] E24 Finally, I would like to see a discussion on the “stability” of the catalogue of the smells. The “traditional” catalogue of smells defined by Martin Fowler (and others) is based on general (and timeless) programming principles. This new catalogue of smells is strongly related to the Android technology and such technology is evolving very rapidly. This means that in the next years some of the smells present now in the catalogue could disappears in mobile apps just because the underlying technology does not allow to implement them anymore.

**Comment by mauricioaniche** [comment]
Tasks from our side:

- [ ] Expand related work (get everything from Suelen's MSc thesis)

**Comment by mauricioaniche** [comment]
@SuelenGC Suelen, no E12, o cara fala "que parece que os dados foram extraídos apenas da opinião de 19 participantes". Vc tem alguma ideia da onde ele tirou essa bizarrice?

**Comment by mauricioaniche** [comment]
Sobre E02, a gente não tem informação sobre quantas empresas e quantas apps... Acho que não precisa na minha opinião. Anos de experiência é mais que bom.

**Comment by mauricioaniche** [comment]
E24, mencionei como trabalhos futuros já

**Comment by SuelenGC** [comment]
Oi @mauricioaniche não sei dizer porque ela concluiu que os dados vieram apenas de 19 participantes. Entranho!

**Comment by mauricioaniche** [comment]
E08 is a stupid comment. I'll ignore it

**Comment by mauricioaniche** [comment]
E21 vou ignorar, nao sei o que fazer
